const atlas = 'Kardiyak anatomi atlası';
const av = 'Ho et al., 2003, PDF pp. 3–4';
const la = 'Ho et al., 2012, PDF pp. 2–3';
const rv = 'Anatomy for right ventricular lead implantation, PDF p. 2';
export const structures = {
  ra: { title: 'Right atrium', description: 'Receives systemic venous blood. Its smooth venous component meets the pectinate muscle region at the terminal crest.', clinical: 'The coronary sinus ostium, tricuspid hinge and tendon of Todaro frame Koch’s triangle. These are landmarks, not visible outlines of conduction tissue.', source: `${atlas}, PDF pp. 12–16; ${av}` },
  la: { title: 'Left atrium', description: 'The most posterior chamber receives pulmonary veins. Atrial muscle sleeves extend over the veins, with variable length and arrangement.', clinical: 'Pulmonary vein anatomy varies. The posterior wall lies near the esophagus, which is omitted from this schematic.', source: `${la}; Ho et al., 2012, PDF p. 8` },
  rv: { title: 'Right ventricle', description: 'An anterior chamber with inlet, trabeculated apical component and outlet. The moderator band crosses from the septomarginal trabeculation toward the anterior papillary muscle.', clinical: 'A projected lead position does not establish septal contact. Trabeculations, valve apparatus and a thin apical wall matter.', source: rv },
  lv: { title: 'Left ventricle', description: 'The systemic pumping chamber lies behind and to the left of the right ventricle. Its inlet is the mitral valve and its outlet leads to the aorta.', clinical: 'Mitral–aortic fibrous continuity adjoins the central fibrous body and membranous septum.', source: `${atlas}, PDF pp. 38–39; ${rv}` },
  aorta: { title: 'Aorta', description: 'The systemic arterial outlet. The aortic root is anterior to the left atrium and closely related to the atrial septal region.', clinical: 'This schematic shows spatial orientation, not a catheter engagement target.', source: la },
  pa: { title: 'Pulmonary trunk', description: 'The right ventricular outlet continues toward the pulmonary circulation. The pulmonary trunk bifurcation is near the left atrial roof.', clinical: 'The right ventricular outflow tract has a distinct muscular architecture.', source: `${rv}; ${la}` },
  svc: { title: 'Superior vena cava', description: 'The superior caval vein enters the upper right atrium. Myocardial sleeves may extend onto its wall.', clinical: 'The sinus nodal region and terminal crest are nearby landmarks.', source: `${atlas}, PDF pp. 15–17` },
  ivc: { title: 'Inferior vena cava', description: 'The inferior caval opening lies at the lower right atrium. The Eustachian valve and ridge are neighboring structures.', clinical: 'The cavotricuspid isthmus spans the region between the inferior caval opening and tricuspid hinge; its contour and thickness vary.', source: 'İnferior sağ atriyal istmus anatomisi, PDF pp. 2–3' },
  lad: {
    title: 'Left anterior descending artery (LAD) • Sol Ön İnen Arter',
    description: 'Sol ana koroner arterden (LMCA, LCC ostiyumu) doğarak sulcus interventricularis anterior (ön interventriküler oluk) boyunca epikardiyal yüzeyde seyreder ve kalbin apeksine (tepesine) ulaşır. Ön-yan duvara diagonal dallar (D1, D2) ve interventriküler septuma dik inen perforatör dallar (S1) verir.',
    clinical: 'KORONER BESLEME ALANI (PERFUSION TERRITORY):\n• (1) Sol Ventrikül Ön Duvarı (Anterior Wall)\n• (2) Kalbin Apeksi (Apex)\n• (3) İnterventriküler Septumun Ön 2/3\'ü\n• (4) Anterolateral Papiller Kas tabanı\n• (5) His-Purkinje dal demetleri (Sağ ve sol dal).\n\nEKG & KLİNİK:\n• V1–V4 derivasyonlarında ST yükselmesi (Ön Yüz / Anterior STEMI).\n• Sol ventrikül pompa gücünün %50\'sinden fazlasını beslediği için tıkanması en yüksek mortalite ve kardiyojenik şok riski taşır ("Dul bırakan / Widowmaker").',
    source: 'American Heart Association Coronary Anatomy; Ho et al., 2003, PDF pp. 2–4'
  },
  rca: {
    title: 'Right coronary artery (RCA) • Sağ Koroner Arter',
    description: 'Aort kökündeki Sağ Koroner Kuspisten (RCC ostiyumu) çıkar ve sulcus coronarius (sağ atriyoventriküler oluk) içinde seyreder. Sağ ventrikül kenarında Akut Marjinal dalı (AM), kalbin arka yüzündeki crux cordis bölgesinde ise PDA (Posterior Descending Artery) dalını vererek arka olukta apekse doğru uzanır.',
    clinical: 'KORONER BESLEME ALANI (PERFUSION TERRITORY):\n• (1) Sağ Ventrikül Serbest Duvarı ve Sağ Atriyum\n• (2) Sol Ventrikül Alt (İnferior / Diyafragmatik) Duvarı (%85-90 sağ-dominant sistemde)\n• (3) İnterventriküler Septumun Arka 1/3\'ü (PDA vasıtasıyla)\n• (4) Sinüs Düğümü (~%60) ve AV Düğümü (~%90 - Koch Üçgeni)\n• (5) Posteromedial Papiller Kas (tek arteryel besleme).\n\nEKG & KLİNİK:\n• DII, DIII, aVF derivasyonlarında ST yükselmesi (İnferior STEMI) ve V3R–V4R (Sağ Ventrikül Tutulumu).\n• AV tam bloklar, bradikardi ve hipotansiyon sık görülür; posteromedial papiller kas rüptürüne bağlı akut mitral yetmezlik gelişebilir.',
    source: 'Sağ atriyoventriküler oluk anatomisi, PDF pp. 4–5; Ho et al., 2003, PDF pp. 3–5'
  },
  lcx: {
    title: 'Left circumflex artery (LCx) • Sol Sirkumfleks Arter',
    description: 'Sol ana koroner arterden (LMCA) ayrılarak sulcus coronarius (sol atriyoventriküler oluk) içinde sol atriyum ile sol ventrikül arasından arkaya doğru döner. Sol ventrikül yan serbest duvarına Obtuse Marginal dallar (OM1, OM2) ve sol atriyal dallar verir.',
    clinical: 'KORONER BESLEME ALANI (PERFUSION TERRITORY):\n• (1) Sol Ventrikül Yan (Lateral) ve Arka-Yan (Posterolateral) Duvarı\n• (2) Sol Atriyum Myokardı\n• (3) Sinüs Düğümü arteri (~%40–45 bireyde)\n• (4) Sol-dominant anatomide (%10-15): Sol ventrikül inferior duvarı, posterior septum ve AV düğüm.\n\nEKG & KLİNİK:\n• DI, aVL, V5–V6 derivasyonlarında ST yükselmesi (Lateral STEMI) ve V7–V9 (Gerçek Arka Yüz / Posterior STEMI).\n• Standart 12 derivasyonlu EKG\'de sessiz kalabilen izole posterior enfarktüslere yol açabilir.',
    source: 'American Heart Association; Ho et al., 2012, PDF pp. 2–3'
  },
  cs: { title: 'Coronary sinus', description: 'A venous channel in the inferior atrioventricular groove that opens into the right atrium near the inferior caval opening.', clinical: 'Its ostium helps identify Koch’s triangle. The Thebesian valve and venous anatomy are variable.', source: 'Coronary sinus and cardiac venous anatomy, PDF p. 3; Ho et al., 2012, PDF pp. 2–3' },
  sa: { title: 'Sinus nodal region', description: 'The sinus nodal region relates to the upper right atrium and terminal crest. The glowing marker represents a region, not its true tissue boundaries.', clinical: 'Conduction tissue is specialized myocardium; colored markers are educational overlays.', source: `${atlas}, PDF pp. 15–17; Ho et al., 2003, PDF p. 1` },
  av: { title: 'AV node • Koch’s triangle', description: 'The compact AV node lies near the apex of Koch’s triangle. The tendon of Todaro, septal tricuspid hinge and coronary sinus ostium define its anatomical landmarks.', clinical: 'The cavotricuspid isthmus and the AV nodal region are different anatomical teaching targets. Neither marker is a treatment prescription.', source: av },
  his: { title: 'His–Purkinje axis', description: 'The penetrating His bundle traverses the central fibrous body. Right and left bundle branches distribute into the ventricles.', clinical: 'Its tissue course varies. The right bundle relates to the septomarginal trabeculation; the left bundle has a subendocardial course.', source: av },
  mitral: { title: 'Mitral valve', description: 'Marks the left atrioventricular junction, connecting the left atrial vestibule to the ventricular inlet.', clinical: 'The mitral isthmus is an atrial region between the left inferior pulmonary vein orifice and mitral annulus; it is not a valve leaflet.', source: 'Ho et al., 2012, PDF p. 7; mini atlas, PDF pp. 38–39' },
  tricuspid: { title: 'Tricuspid valve', description: 'The right atrioventricular valve has septal, anterior and inferior leaflets with chordal attachments to the ventricular apparatus.', clinical: 'The septal hinge is a landmark for Koch’s triangle. Lead paths must be understood in relation to the valve and subvalvar apparatus.', source: `${rv}; ${av}` },
  lcc: { title: 'Left coronary cusp & sinus (LCC)', description: 'The aortic sinus from which the left main coronary artery originates. It lies in close anterior-left proximity to the pulmonary trunk root.', clinical: 'The LCC is adjacent to the left ventricular summit and pulmonary trunk wall. Arrhythmias originating from the LCC / RVOT junction have critical ablation implications regarding the left main ostium.', source: 'Ho et al., 2003, PDF pp. 2–4' },
  rcc: { title: 'Right coronary cusp & sinus (RCC)', description: 'The anterior aortic sinus giving rise to the right coronary artery. It directly faces and abuts the posterior right ventricular outflow tract (RVOT) and posterior pulmonary root wall.', clinical: 'The RCC lies directly behind the pulmonary valve and infundibulum. Catheter ablation in the RVOT can be transmitted to the RCC due to their close wall-to-wall contact.', source: 'Ho et al., 2003, PDF pp. 3–5' },
  ncc: { title: 'Non-coronary cusp & sinus (NCC)', description: 'The posterior-septal aortic sinus which typically lacks a coronary artery ostium. It is in intimate contact with the interatrial septum and membranous septum.', clinical: 'The NCC borders the central fibrous body and the AV conduction bundle (His bundle) immediately inferiorly and posteriorly. Ablation here carries heart block risk.', source: 'Ho et al., 2003, PDF pp. 3–4; mini atlas, PDF pp. 38–39' },
  micro: { title: 'Myocardium • conceptual micro view', description: 'Working cardiac myocytes and specialized conduction myocytes form distinct, connected tissue systems. Fiber arrangement changes across regions and depth.', clinical: 'This enlarged diagram is not histology, a tissue sample, or a measured fiber field. It cannot predict conduction velocity, fibrosis or ablation depth.', source: 'Ho et al., 2003, PDF pp. 4–5, 8; Ho et al., 2012, PDF p. 6' }
};
export const lessons = {
  angiography: { title: 'Coronary angiography', intro: 'Explore arterial anatomy and projection. Catheter route is illustrative, not X-ray physics or a diagnostic angiogram.', steps: [
    { title: 'Orient the root', text: 'Identify the aorta and distinguish coronary arteries from cardiac veins. Real coronary angiography uses X-rays and contrast to display arterial lumens.', landmark: 'aorta' },
    { title: 'Follow the left system', text: 'Trace the idealized LAD toward the apex and circumflex around the left atrioventricular groove.', landmark: 'lad' },
    { title: 'Compare viewpoints', text: 'Rotate the model to see how branches overlap in a two-dimensional projection. Camera presets illustrate viewing directions, not calibrated fluoroscopy.', landmark: 'rca' },
    { title: 'Interpret the limitation', text: 'Replay the catheter route illustration. No stenosis, pressure, flow reserve or real catheter engagement is measured.', landmark: 'lcx' }
  ] },
  ablation: { title: 'EP anatomy • ablation concepts', intro: 'Recognize distinct anatomical regions. Highlighting a region does not simulate mapping, energy delivery or lesion formation.', steps: [
    { title: 'Find the right atrial landmarks', text: 'Locate the inferior caval opening and tricuspid hinge. The intervening cavotricuspid isthmus has variable pouches and muscular thickness.', landmark: 'ivc' },
    { title: 'Separate Koch’s triangle', text: 'Locate the AV nodal region near the triangle’s apex and the coronary sinus opening near its base. Do not equate this region with the cavotricuspid isthmus.', landmark: 'av' },
    { title: 'Explore pulmonary vein sleeves', text: 'Rotate to the posterior left atrium. Variable myocardial sleeves around pulmonary veins help explain their electrophysiological relevance.', landmark: 'la' },
    { title: 'Link anatomy to physiology', text: 'Ablation concepts require electrical evidence as well as anatomy. This diagram provides no electrograms, contact feedback or proof of conduction block.', landmark: 'his' }
  ] },
  pacemaker: { title: 'Pacing lead • anatomy walkthrough', intro: 'Follow a conceptual transvenous lead route. This is not an implantation trainer or device programming guide.', steps: [
    { title: 'Understand venous entry', text: 'The illustrated route approaches the right atrium through the superior vena cava. Access technique and complications are outside this demonstration.', landmark: 'svc' },
    { title: 'Recognize the valve plane', text: 'Observe the relationship between the right atrium, tricuspid valve and right ventricular inlet. The real valve apparatus is more complex than this ring.', landmark: 'tricuspid' },
    { title: 'Compare RV regions', text: 'Distinguish inlet, apex, septum and outflow tract. A lead tip drawn over a septal silhouette does not establish true septal fixation.', landmark: 'rv' },
    { title: 'Recognize verification needs', text: 'Actual implantation requires imaging and electrical checks. This walkthrough has no capture threshold, sensing, impedance, fixation or perforation model.', landmark: 'his' }
  ] }
};
