import { ANGINA_DRUGS, ANGINA_SOURCES } from './angina-data.js';
import './angina-panel.css';
import { createAnginaVisual } from './angina-visual.js';
const text = (tr, en) => ({ tr, en });
const TARGETS = {
  rate: text('Kalp hızı ↓', 'Heart rate ↓'), contractility: text('Kontraktilite ↓', 'Contractility ↓'), afterload: text('Ard yük ↓', 'Afterload ↓'), preload: text('Ön yük ↓', 'Preload ↓'), coronary: text('Koroner vazodilatasyon', 'Coronary vasodilation'), diastolic: text('Diyastolik gerilim ↓', 'Diastolic tension ↓'), metabolic: text('Metabolik verimlilik', 'Metabolic efficiency'),
};
const PHENOTYPES = {
  obstructive: { title: text('Obstrüktif / efor', 'Obstructive / exertional'), detail: text('Sabit epikardiyal darlık, artan talepte koroner akım rezervini kısıtlayabilir. Hız, kontraktilite ve duvar gerilimini azaltma semptomlara yardım eder. Semptom giderme ile tromboz/ASCVD olaylarını önleme farklı amaçlardır.', 'Fixed epicardial narrowing can limit coronary flow reserve during increased demand. Reducing rate, contractility and wall tension can relieve symptoms. Symptom relief and prevention of thrombosis/ASCVD events are different goals.') },
  vasospastic: { title: text('Vazospastik', 'Vasospastic'), detail: text('Geçici koroner spazm arzı azaltır. Kalsiyum kanal blokerleri ve nitratların vazodilatasyonu önemlidir. Beta blokerler, özellikle seçici olmayanlar, spazmı kötüleştirebilir. Aynı efor anjinası yaklaşımı otomatik uygulanmaz.', 'Transient coronary spasm reduces supply. Vasodilation with calcium channel blockers and nitrates matters. Beta blockers, especially nonselective agents, may worsen spasm. The exertional-angina approach is not automatically applied.') },
  microvascular: { title: text('Mikrovasküler', 'Microvascular'), detail: text('Küçük damar disfonksiyonu, azalmış akım rezervi veya mikrovasküler spazm bulunabilir; büyük arter açık olabilir. Tedavi endotype göre değişir, tüm ilaçların yararı aynı değildir. Ranolazinin endoteli düzelttiği genellemesi kanıtlanmış sınıf etkisi olarak gösterilmez.', 'Small-vessel dysfunction, reduced flow reserve or microvascular spasm may occur despite a patent large artery. Therapy depends on endotype; benefits are not identical for every drug. Endothelial improvement with ranolazine is not presented as an established class effect.') },
};
export function createAnginaPanel({ mount, getLang }) {
  let selected = 'nitrate', phenotype = 'obstructive', focus = '';
  const root = document.createElement('section'); root.className = 'anginalab';
  root.innerHTML = `<p class="anginalab-eyebrow"></p><h2></h2><p class="anginalab-intro"></p><div class="anginalab-drugs" role="group"></div><div class="anginalab-layout"><div class="anginalab-map"><div class="anginalab-demand"><h3></h3><div></div></div><div data-angina-visual></div><div class="anginalab-supply"><h3></h3><div></div></div><p class="anginalab-legend"></p></div><article class="anginalab-detail" aria-live="polite"><h3></h3><p class="anginalab-examples"></p></article></div><section class="anginalab-phenotype"><h3></h3><div role="group"></div><p aria-live="polite"></p></section><details class="anginalab-corrections"><summary></summary><ul></ul></details><details class="anginalab-sources"><summary></summary><ul></ul></details>`;
  mount.append(root);
  const visual = createAnginaVisual({ mount: root.querySelector('[data-angina-visual]'), getLang, onFocus: id => { focus = id; refresh(); } });
  const t = value => value[getLang() === 'en' ? 'en' : 'tr'];
  const buttons = new Map(), targetNodes = new Map(), phenotypeButtons = new Map(), fields = new Map();
  for (const item of ANGINA_DRUGS) { const button = document.createElement('button'); button.type = 'button'; button.dataset.anginaDrug = item.id; button.addEventListener('click', () => { selected = item.id; focus = ''; refresh(); }); root.querySelector('.anginalab-drugs').append(button); buttons.set(item.id, button); }
  for (const [id, label] of Object.entries(TARGETS)) { const node = document.createElement('button'); node.type = 'button'; node.dataset.anginaTarget = id; node.textContent = t(label); node.addEventListener('click', () => { focus = id; refresh(); }); root.querySelector(id === 'coronary' ? '.anginalab-supply > div' : '.anginalab-demand > div').append(node); targetNodes.set(id, node); }
  for (const id of Object.keys(PHENOTYPES)) { const button = document.createElement('button'); button.type = 'button'; button.dataset.anginaPhenotype = id; button.addEventListener('click', () => { phenotype = id; refresh(); }); root.querySelector('.anginalab-phenotype [role=group]').append(button); phenotypeButtons.set(id, button); }
  for (const key of ['mechanism', 'context', 'risk', 'monitor']) { const div = document.createElement('div'); div.dataset.anginaField = key; div.innerHTML = '<h4></h4><p></p>'; root.querySelector('article').append(div); fields.set(key, div); }
  for (const source of ANGINA_SOURCES) { const li = document.createElement('li'), node = document.createElement(source.url ? 'a' : 'span'); node.textContent = source.title; if (source.url) { node.href = source.url; node.target = '_blank'; node.rel = 'noopener noreferrer'; } li.append(node); root.querySelector('.anginalab-sources ul').append(li); }
  function refresh() {
    const active = ANGINA_DRUGS.find(item => item.id === selected);
    root.querySelector('.anginalab-eyebrow').textContent = t(text('ANTİANGİNAL LABORATUVAR', 'ANTIANGINAL LAB'));
    root.querySelector('h2').textContent = t(text('Oksijen arzı, talep ve ilaç hedefleri', 'Oxygen supply, demand and drug targets'));
    root.querySelector('.anginalab-intro').textContent = t(text('İlaç grubunu seçin. Vurgulu hedefler tipik mekanizmayı gösterir; doz, kan basıncı veya koroner akım hesaplanmaz.', 'Select a drug class. Highlighted targets show typical mechanisms; no dose, blood pressure or coronary flow is calculated.'));
    root.querySelector('.anginalab-drugs').setAttribute('aria-label', t(text('Antianginal ilaç grupları', 'Antianginal drug classes')));
    for (const [id, button] of buttons) { button.textContent = t(ANGINA_DRUGS.find(item => item.id === id).name); button.setAttribute('aria-pressed', String(selected === id)); }
    for (const [id, node] of targetNodes) { node.textContent = `${active.targets.includes(id) ? '● ' : ''}${t(TARGETS[id])}`; node.classList.toggle('is-active', active.targets.includes(id)); node.classList.toggle('is-focus', focus === id); node.setAttribute('aria-pressed', String(focus === id)); }
    root.querySelector('.anginalab-demand h3').textContent = t(text('Talep / miyokard etkisi', 'Demand / myocardial effects'));
    root.querySelector('.anginalab-supply h3').textContent = t(text('Arz / koroner tonus', 'Supply / coronary tone'));
    visual.update({ targets: active.targets, focus, phenotype, phenotypeTitle: t(PHENOTYPES[phenotype].title) });
    visual.setTitle(`${t(active.name)}: ${active.targets.map(id => t(TARGETS[id])).join(', ')}; ${t(PHENOTYPES[phenotype].title)}`);
    root.querySelector('.anginalab-legend').textContent = t(text('● Altın hedef: seçili sınıf etkisi. Mekanizma özeti, etki büyüklüğü veya kanıtlanmış sağkalım faydası değildir.', '● Gold target: selected class effect. Mechanism summary, not effect size or proven survival benefit.'));
    root.querySelector('article h3').textContent = t(active.name); root.querySelector('.anginalab-examples').textContent = t(active.examples);
    const labels = { mechanism: text('Mekanizma', 'Mechanism'), context: text('Kullanım / kanıt', 'Use / evidence'), risk: text('Güvenlik', 'Safety'), monitor: text('İzlem', 'Monitoring') };
    for (const [id, node] of fields) { node.querySelector('h4').textContent = t(labels[id]); node.querySelector('p').textContent = t(active[id]); }
    root.querySelector('.anginalab-phenotype h3').textContent = t(text('Anjina fenotipi', 'Angina phenotype'));
    root.querySelector('.anginalab-phenotype [role=group]').setAttribute('aria-label', t(text('Anjina fenotipi', 'Angina phenotype')));
    for (const [id, button] of phenotypeButtons) { button.textContent = t(PHENOTYPES[id].title); button.setAttribute('aria-pressed', String(id === phenotype)); }
    root.querySelector('.anginalab-phenotype p').textContent = t(PHENOTYPES[phenotype].detail);
    root.querySelector('.anginalab-corrections summary').textContent = t(text('Referans şemaların düzeltmeleri', 'Corrections to reference diagrams'));
    const corrections = [text('İvabradin If akımını artırmaz, inhibe eder. Sinüs düğümüne etki eder; AF hız kontrolü ilacı değildir.', 'Ivabradine inhibits, rather than increases, If current. It acts on the sinus node; not an AF rate-control drug.'), text('DHP ve non-DHP aynı hemodinamik etkiyle birleştirilmedi. Non-DHP/beta bloker birlikteliğinde bradikardi/AV blok, HFrEF içinde negatif inotropi önemlidir.', 'DHP and non-DHP are not assigned identical hemodynamic effects. Non-DHP/beta-blocker combinations risk bradycardia/AV block; negative inotropy matters in HFrEF.'), text('Ranolazin geç Na akımını baskılar; antianginal mekanizmanın tüm ayrıntıları kesin değildir. Endotel düzelmesi kanıtlanmış genel etki olarak verilmez.', 'Ranolazine inhibits late sodium current; its full antianginal mechanism is not established. Endothelial improvement is not presented as a proven general effect.'), text('Eski nitrit/siyanür kutusu güncel akut tedavi algoritması değildir; amil nitrit rutin anjina sınıfı olarak eklenmedi. Nitrat toleransı ile akut dilaltı ve uzun etkili kullanım bağlamları ayrılır.', 'The old nitrite/cyanide box is not a contemporary emergency treatment algorithm; amyl nitrite was not added as routine angina therapy. Nitrate tolerance and acute sublingual versus long-acting contexts are distinguished.'), text('İlaçların semptom etkisi, plak/tromboz riskinin azaltılmasıyla eş tutulmaz. Şema eksiksiz tedavi algoritması değildir; akut göğüs ağrısı triyajı içermez.', 'Symptom effects are not equated with plaque/thrombosis risk reduction. This is not a complete treatment algorithm and contains no acute chest-pain triage.')];
    root.querySelector('.anginalab-corrections ul').replaceChildren(...corrections.map(value => { const li = document.createElement('li'); li.textContent = t(value); return li; }));
    root.querySelector('.anginalab-sources summary').textContent = t(text('Kaynaklar', 'Sources'));
  }
  refresh(); return { refresh };
}
