/** Educational class-level effects. Calcium labels describe urine, not serum. */
const text = (tr, en) => ({ tr, en });

export const DIURETIC_SOURCES = [
  { id: 'furosemide-label', title: 'DailyMed: Furosemide, clinical pharmacology', url: 'https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=f3173c0d-2b62-7c7b-e053-2995a90ada05' },
  { id: 'torsemide-label', title: 'DailyMed: Torsemide, clinical pharmacology', url: 'https://www.dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=13d851b6-3355-4541-93e8-73cdaf0f13d1' },
  { id: 'bumetanide-label', title: 'DailyMed: Bumetanide, clinical pharmacology', url: 'https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=551918e1-96c4-453a-870c-61b282882206' },
  { id: 'lippincott-diuretics', title: 'Lippincott Illustrated Reviews: Pharmacology, 7th ed., Chapter 17: Diuretics' },
  { id: 'cardiac-drugs', title: 'Cardiac Drugs, diuretic overview' },
  { id: 'mannitol-label', title: 'DailyMed: Mannitol injection, prescribing information', url: 'https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=8ad3145e-00e7-4412-b9a5-06f00f264f30' },
  { id: 'spiro-label', title: 'DailyMed: Spironolactone, prescribing information', url: 'https://dailymed.nlm.nih.gov/dailymed/lookup.cfm?setid=ae0dcb4e-63df-459c-8e60-0caa817b8135' },
  { id: 'dorzolamide-label', title: 'DailyMed: Dorzolamide ophthalmic solution', url: 'https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=9bc35df4-2d41-4160-8dae-7eea3e4ff0ce' },
  { id: 'ethacrynic-label', title: 'DailyMed: Ethacrynic acid, prescribing information', url: 'https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=d400d264-c231-4bdf-8180-eb11ab4e9f29' },
  { id: 'kdigo-aki', title: 'KDIGO: Acute kidney injury and acute kidney disease guidelines', url: 'https://kdigo.org/guidelines/acute-kidney-injury/' },
  { id: 'hypercalcemia-guideline', title: 'Endocrine Society: Treatment of Hypercalcemia of Malignancy in Adults (2023)', url: 'https://academic.oup.com/jcem/article/108/3/507/6916871' },
  { id: 'amiloride-lithium', title: 'Bedford et al.: Lithium-induced nephrogenic diabetes insipidus, renal effects of amiloride (2008)', url: 'https://pubmed.ncbi.nlm.nih.gov/18596116/' },
  { id: 'triamterene-label', title: 'DailyMed: Triamterene/hydrochlorothiazide, renal stone warning', url: 'https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=189ad040-07e9-42a5-854c-67633367da74' },
];

export const DIURETIC_CLASSES = [
  {
    id: 'ca', title: text('Karbonik anhidraz inhibitörleri', 'Carbonic anhydrase inhibitors'),
    examples: text('Asetazolamid (sistemik); dorzolamid (göz damlası)', 'Acetazolamide (systemic); dorzolamide (eye drops)'),
    segments: ['proximal'],
    mechanism: text('Sistemik asetazolamid proksimal tübülde karbonik anhidrazı baskılar; NaHCO₃ geri emilimi azalır, bikarbonatüri gelişir. Dorzolamid gözde aköz hümör üretimini azaltır; renal diüretik değildir.', 'Systemic acetazolamide inhibits proximal tubular carbonic anhydrase, reducing NaHCO₃ reabsorption and increasing urinary bicarbonate. Ophthalmic dorzolamide reduces aqueous humor production; it is not a renal diuretic.'),
    uses: [text('Glokom: sistemik asetazolamid veya topikal dorzolamid', 'Glaucoma: systemic acetazolamide or topical dorzolamide'), text('Asetazolamid: akut dağ hastalığının önlenmesi', 'Acetazolamide: prevention of acute mountain sickness'), text('Asetazolamid: seçilmiş metabolik alkaloz olguları', 'Acetazolamide: selected cases of metabolic alkalosis')],
    risks: [text('Asetazolamid: hiperkloremik metabolik asidoz ve hipokalemi', 'Acetazolamide: hyperchloremic metabolic acidosis and hypokalemia'), text('Parestezi, böbrek taşı; sülfonamid aşırı duyarlılığı', 'Paresthesias, renal stones; sulfonamide hypersensitivity'), text('Dorzolamid: gözde yanma/batma; sistemik emilim ve aşırı duyarlılık mümkündür', 'Dorzolamide: ocular burning/stinging; systemic absorption and hypersensitivity are possible')],
    monitor: text('Sistemik kullanımda K⁺, Na⁺, HCO₃⁻ ve böbrek işlevi; göz tedavisinde göz içi basıncı.', 'Systemic use: K⁺, Na⁺, HCO₃⁻ and renal function; ocular therapy: intraocular pressure.'),
    effects: { potassium: 'down', calcium: 'variable', acid: 'acidosis' },
    sourceIds: ['lippincott-diuretics', 'dorzolamide-label'],
  },
  {
    id: 'loop', title: text('Loop diüretikleri', 'Loop diuretics'),
    examples: text('Furosemid, torsemid, bumetanid; etakrinik asit', 'Furosemide, torsemide, bumetanide; ethacrynic acid'),
    segments: ['ascending'],
    mechanism: text('Henle kulpunun kalın çıkan kolunda NKCC2 (Na⁺/K⁺/2Cl⁻) taşıyıcısını baskılar. Güçlü natriürez; idrarda Ca²⁺ ve Mg²⁺ atılımı artar.', 'Inhibit NKCC2 (Na⁺/K⁺/2Cl⁻) in the thick ascending limb. Strong natriuresis with increased urinary Ca²⁺ and Mg²⁺ excretion.'),
    uses: [text('Kalp yetersizliği ve akut pulmoner ödemde konjesyon', 'Congestion in heart failure and acute pulmonary edema'), text('Böbrek hastalığında hacim yükü; dirençli ödem', 'Volume overload in renal disease; resistant edema'), text('AKI içinde yalnız hacim yükü kontrolü; böbrek hasarını düzeltmez', 'In AKI, control of volume overload; does not reverse kidney injury'), text('Hiperkalsemide rutin ilk seçenek değildir; hidrasyon sırasında hacim yükü için seçilmiş kullanım', 'Not routine first-line therapy for hypercalcemia; selected use for fluid overload during hydration')],
    risks: [text('Hipokalemi, metabolik alkaloz, hipomagnezemi', 'Hypokalemia, metabolic alkalosis, hypomagnesemia'), text('Hipovolemi, hipotansiyon, hiperürisemi/gut', 'Hypovolemia, hypotension, hyperuricemia/gout'), text('Ototoksisite; etakrinik asitte risk özellikle önemlidir', 'Ototoxicity, particularly important with ethacrynic acid'), text('Furosemidde aşırı duyarlılık mümkündür; etakrinik asit sülfonamid değildir', 'Hypersensitivity can occur with furosemide; ethacrynic acid is not a sulfonamide')],
    monitor: text('K⁺, Na⁺, Mg²⁺, böbrek işlevi, kan basıncı, kilo ve sıvı dengesi; işitme yakınmaları.', 'K⁺, Na⁺, Mg²⁺, renal function, blood pressure, weight and fluid balance; hearing symptoms.'),
    effects: { potassium: 'down', calcium: 'urine-up', acid: 'alkalosis' },
    sourceIds: ['lippincott-diuretics', 'cardiac-drugs', 'ethacrynic-label', 'kdigo-aki', 'hypercalcemia-guideline'],
  },
  {
    id: 'thiazide', title: text('Tiyazid ve tiyazid benzerleri', 'Thiazide and thiazide-like diuretics'),
    examples: text('Hidroklorotiyazid, indapamid, klortalidon', 'Hydrochlorothiazide, indapamide, chlorthalidone'),
    segments: ['distal'],
    mechanism: text('Erken distal tübülde NCC (Na⁺/Cl⁻) taşıyıcısını baskılar; idrarda Ca²⁺ atılımını azaltır.', 'Inhibit NCC (Na⁺/Cl⁻) in the early distal tubule; reduce urinary Ca²⁺ excretion.'),
    uses: [text('Hipertansiyon', 'Hypertension'), text('Dirençli konjesyonda loop diüretiğine ek tedavi', 'Add-on to loop diuretics for resistant congestion'), text('Seçilmiş hiperkalsiürili tekrarlayan kalsiyum taşı olguları; tüm taş tipleri için değil', 'Selected recurrent calcium stones with hypercalciuria; not all stone types'), text('Nefrojenik diabetes insipidus', 'Nephrogenic diabetes insipidus')],
    risks: [text('Hipokalemi, metabolik alkaloz; hiponatremi ve hipomagnezemi', 'Hypokalemia, metabolic alkalosis; hyponatremia and hypomagnesemia'), text('Hiperürisemi/gut, hiperkalsemi', 'Hyperuricemia/gout, hypercalcemia'), text('Glukoz ve lipid artışı görülebilir; hipovolemi', 'Glucose and lipid increases may occur; hypovolemia'), text('Sülfonamid aşırı duyarlılığı mümkündür; antibiyotik alerjisi otomatik çapraz alerji demek değildir', 'Sulfonamide hypersensitivity is possible; antibiotic allergy does not imply automatic cross-allergy')],
    monitor: text('Na⁺, K⁺, Mg²⁺, Ca²⁺, böbrek işlevi, kan basıncı; glukoz ve ürik asit.', 'Na⁺, K⁺, Mg²⁺, Ca²⁺, renal function, blood pressure; glucose and uric acid.'),
    effects: { potassium: 'down', calcium: 'urine-down', acid: 'alkalosis' },
    sourceIds: ['lippincott-diuretics', 'cardiac-drugs'],
  },
  {
    id: 'mra', title: text('Mineralokortikoid reseptör antagonistleri', 'Mineralocorticoid receptor antagonists'),
    examples: text('Spironolakton, eplerenon', 'Spironolactone, eplerenone'), segments: ['collecting'],
    mechanism: text('Toplayıcı tübülde aldosteron reseptörünü bloke eder; Na⁺ tutulması ile K⁺ ve H⁺ atılımını azaltır.', 'Block aldosterone receptors in the collecting tubule, reducing Na⁺ retention and K⁺/H⁺ secretion.'),
    uses: [text('Azalmış EF ile kalp yetersizliği: seçilmiş hastalarda prognoz yararı', 'Heart failure with reduced EF: outcome benefit in eligible patients'), text('Hiperaldosteronizm; spironolakton ile siroza bağlı asit', 'Hyperaldosteronism; spironolactone for cirrhotic ascites'), text('Dirençli hipertansiyon; K⁺ kaybettiren diüretiğe seçilmiş ek kullanım', 'Resistant hypertension; selected add-on to potassium-wasting diuretics')],
    risks: [text('Hiperkalemi ve metabolik asidoz; böbrek bozukluğunda risk artar', 'Hyperkalemia and metabolic acidosis; greater risk with renal impairment'), text('Spironolakton: jinekomasti ve adet düzensizliği; eplerenonda endokrin etkiler daha az', 'Spironolactone: gynecomastia and menstrual irregularities; fewer endocrine effects with eplerenone')],
    monitor: text('K⁺ ve kreatinin/eGFR; K⁺ takviyesi ve RAAS ilaçları ile etkileşimler.', 'K⁺ and creatinine/eGFR; interactions with potassium supplements and RAAS drugs.'),
    effects: { potassium: 'up', calcium: 'neutral', acid: 'acidosis' }, sourceIds: ['lippincott-diuretics', 'cardiac-drugs', 'spiro-label'],
  },
  {
    id: 'enac', title: text('ENaC kanal blokerleri', 'ENaC channel blockers'),
    examples: text('Amilorid, triamteren', 'Amiloride, triamterene'), segments: ['collecting'],
    mechanism: text('Toplayıcı tübülde epitel Na⁺ kanalını doğrudan bloke eder; aldosterondan bağımsız K⁺ koruyucu etki.', 'Directly block epithelial Na⁺ channels in the collecting tubule; potassium-sparing effect independent of aldosterone.'),
    uses: [text('Loop veya tiyazid ile K⁺ kaybını azaltan ek tedavi', 'Add-on to reduce potassium loss with loop or thiazide diuretics'), text('Lityuma bağlı nefrojenik diabetes insipidus: esas olarak amilorid; triamterene genellenmez', 'Lithium-induced nephrogenic diabetes insipidus: principally amiloride; not generalized to triamterene')],
    risks: [text('Hiperkalemi ve metabolik asidoz', 'Hyperkalemia and metabolic acidosis'), text('Triamteren: böbrek taşı riski', 'Triamterene: risk of renal stones')],
    monitor: text('K⁺, böbrek işlevi ve sıvı dengesi; lityum kullanılıyorsa lityum düzeyi.', 'K⁺, renal function and fluid balance; lithium level when taking lithium.'),
    effects: { potassium: 'up', calcium: 'neutral', acid: 'acidosis' }, sourceIds: ['lippincott-diuretics', 'amiloride-lithium', 'triamterene-label'],
  },
  {
    id: 'osmotic', title: text('Osmotik diüretikler', 'Osmotic diuretics'),
    examples: text('Mannitol (intravenöz)', 'Mannitol (intravenous)'), segments: ['proximal', 'descending'],
    mechanism: text('Filtre edilen, az geri emilen mannitol tübül sıvısının ozmolalitesini artırır; su geri emilimini azaltır. Önce damar içi hacmi genişletebilir.', 'Filtered, poorly reabsorbed mannitol increases tubular fluid osmolality and reduces water reabsorption. It can initially expand intravascular volume.'),
    uses: [text('Seçilmiş intrakraniyal basınç artışı/serebral ödem', 'Selected increased intracranial pressure/cerebral edema'), text('Artmış göz içi basıncını azaltma', 'Reduction of elevated intraocular pressure')],
    risks: [text('Başlangıçta hipervolemi ve pulmoner ödem; sonra dehidratasyon/hipovolemi', 'Initial hypervolemia and pulmonary edema; later dehydration/hypovolemia'), text('Na⁺ ve diğer elektrolit bozuklukları; akut böbrek hasarı', 'Sodium and other electrolyte disturbances; acute kidney injury'), text('Anüri veya mevcut ağır pulmoner konjesyon/ödemde kontrendike; oligüri tek başına kullanım gerekçesi değildir', 'Contraindicated in anuria or pre-existing severe pulmonary congestion/edema; oliguria alone is not an indication')],
    monitor: text('Ozmolalite, Na⁺/K⁺, böbrek işlevi, idrar çıkışı; kalp-akciğer durumu ve sıvı dengesi.', 'Osmolality, Na⁺/K⁺, renal function, urine output; cardiopulmonary status and fluid balance.'),
    effects: { potassium: 'variable', calcium: 'variable', acid: 'variable' }, sourceIds: ['lippincott-diuretics', 'mannitol-label'],
  },
];
