// Texts of the slow pathway mapping panel (koch-sp-panel.js). {r} = A:V ratio.
export const KOCH_SP_TEXT = Object.freeze({
  tr: {
    title: 'Yavaş yol haritalama',
    kicker: 'KOCH ÜÇGENİ · SİNÜS RİTMİ',
    intro: 'Şemaya tıklayın, ucu sürükleyin ya da ok tuşlarını kullanın. 3B kateter, floroskopi ve ablasyon sinyali birlikte değişir.',
    schematic: 'Koch üçgeni şeması (RAO bakış); kateter ucunu yerleştirmek için tıklayın',
    tipLabel: 'Ablasyon kateteri ucu',
    labels: { todaro: 'Todaro tendonu', annulus: 'Triküspit anulus', cs: 'CS', avn: 'AVN', his: 'His', fo: 'FO', ivc: 'İVK', fast: 'Hızlı yol', slow: 'Yavaş yol', tcv: 'TV' },
    legend: [['slow', 'Yavaş yol (hedef)'], ['fast', 'Hızlı yol girişi'], ['avn', 'Kompakt AVN'], ['his', 'His']],
    egm: 'Ablasyon kateteri kaydı',
    egmAria: 'Sentetik intrakardiyak kayıt: II, HRA, His, CS 9-10, CS 1-2, ablasyon distal ve proksimal',
    ratio: 'A:V (ABL d)',
    hisPotential: 'His potansiyeli',
    slowPotential: 'Yavaş yol potansiyeli',
    present: 'var',
    absent: 'yok',
    height: 'Yükseklik',
    heightValue: ['taban', 'alt', 'orta', 'üst', 'apeks'],
    zones: {
      target: 'Uygun bölge',
      atrial: 'Fazla atriyal',
      ventricular: 'Fazla ventriküler',
      cs: 'CS ağzı',
      mid: 'Orta septum',
      fast: 'Hızlı yol',
      his: 'His / AV düğüm'
    },
    advice: {
      target: 'Küçük, parçalı A ve büyük V (A:V {r}), His potansiyeli yok. Yavaş yol ablasyonu burada, tabandan başlar.',
      atrial: 'A büyük (A:V {r}): uç atriyal tarafta, Todaro ya da CS ağzına yakın. Ucu triküspit anulusa doğru ilerletin.',
      ventricular: 'A neredeyse yok (A:V {r}): uç anulusu geçmiş, ventrikül tarafında. Ucu biraz atriyuma geri çekin.',
      cs: 'Uç CS ağzında: A büyük, kateter sinüse kayabilir. Biraz öne, anulusa doğru gelin.',
      mid: 'Orta septum: AV düğüme yaklaşılıyor, AV blok riski artar. Önce tabandan deneyin; gerekirse kademeli yükselin.',
      fast: 'Hızlı yol girişi (Todaro üstü, fossa tarafı): RF burada hızlı yolu ve AV iletimini bozabilir. Kaçının.',
      his: 'His potansiyeli kayıtta: kompakt AV düğüm ve His bölgesi. RF tam AV blok yapabilir. Kaçının.'
    },
    target: 'Hedefe git',
    views: 'Floroskopide göster',
    rao: 'RAO 30 floro',
    lao: 'LAO 45 floro',
    view3d: '3B görünüm',
    viewHint: 'RAO kateterin yüksekliğini (His ile CS arası), LAO septal mi lateral mi durduğunu gösterir.',
    note: 'Öğretim modeli: sinyaller konuma göre kurgulanmıştır, hasta kaydı değildir. Tek başına konum kuralı değildir; gerçek ablasyonda floroskopi, sinyaller ve RF sırasında kavşak ritmi birlikte değerlendirilir.',
    source: 'Kaynak: Kardiyopedi AVNRT ablasyonu dersi; Jackman ve ark. N Engl J Med 1992; Haïssaguerre ve ark. Circulation 1992; Koch üçgeni şeması Mayo 2009 çiziminden uyarlanarak yeniden çizildi.'
  },
  en: {
    title: 'Slow pathway mapping',
    kicker: 'TRIANGLE OF KOCH · SINUS RHYTHM',
    intro: 'Click the schematic, drag the tip or use the arrow keys. The 3D catheter, fluoroscopy and the ablation signal change together.',
    schematic: 'Triangle of Koch schematic (RAO view); click to place the catheter tip',
    tipLabel: 'Ablation catheter tip',
    labels: { todaro: 'Tendon of Todaro', annulus: 'Tricuspid annulus', cs: 'CS', avn: 'AVN', his: 'His', fo: 'FO', ivc: 'IVC', fast: 'Fast pathway', slow: 'Slow pathway', tcv: 'TV' },
    legend: [['slow', 'Slow pathway (target)'], ['fast', 'Fast pathway input'], ['avn', 'Compact AVN'], ['his', 'His']],
    egm: 'Ablation catheter recording',
    egmAria: 'Synthetic intracardiac recording: II, HRA, His, CS 9-10, CS 1-2, ablation distal and proximal',
    ratio: 'A:V (ABL d)',
    hisPotential: 'His potential',
    slowPotential: 'Slow pathway potential',
    present: 'present',
    absent: 'absent',
    height: 'Height',
    heightValue: ['base', 'low', 'mid', 'high', 'apex'],
    zones: {
      target: 'Suitable site',
      atrial: 'Too atrial',
      ventricular: 'Too ventricular',
      cs: 'CS ostium',
      mid: 'Midseptum',
      fast: 'Fast pathway',
      his: 'His / AV node'
    },
    advice: {
      target: 'Small, fractionated A and a large V (A:V {r}), no His potential. Slow pathway ablation starts here, at the base.',
      atrial: 'Large A (A:V {r}): the tip is on the atrial side, near Todaro or the CS ostium. Advance it toward the tricuspid annulus.',
      ventricular: 'Almost no A (A:V {r}): the tip is past the annulus, on the ventricular side. Pull it back slightly toward the atrium.',
      cs: 'The tip is at the CS ostium: large A, and the catheter may slip into the sinus. Move a little forward, toward the annulus.',
      mid: 'Midseptum: approaching the AV node, the risk of AV block rises. Start at the base; move up step by step only if needed.',
      fast: 'Fast pathway input (above Todaro, on the fossa side): RF here can damage the fast pathway and AV conduction. Avoid.',
      his: 'A His potential is recorded: compact AV node and His region. RF can cause complete AV block. Avoid.'
    },
    target: 'Go to target',
    views: 'Show on fluoroscopy',
    rao: 'RAO 30 fluoro',
    lao: 'LAO 45 fluoro',
    view3d: '3D view',
    viewHint: 'RAO shows the height of the catheter (between His and CS), LAO whether it sits septal or lateral.',
    note: 'Teaching model: signals are constructed from the position, not a patient recording. Not a localization rule on its own; real ablation weighs fluoroscopy, signals and junctional rhythm during RF together.',
    source: 'Source: Kardiyopedi AVNRT ablation lecture; Jackman et al. N Engl J Med 1992; Haïssaguerre et al. Circulation 1992; the Koch triangle schematic is redrawn after the Mayo 2009 illustration.'
  }
});
