const text = (tr, en) => ({ tr, en });
export const PHYSIOLOGY_TEXT = {
  title: text('Görsel fizyoloji rehberi', 'Visual physiology guide'),
  topics: { calcium: text('Ca²⁺ → kasılma', 'Ca²⁺ → contraction'), conduction: text('AV iletim', 'AV conduction'), pump: text('Pompa eğrileri', 'Pump curves'), pv: text('P-V: fazlar ve iş', 'P-V: phases and work'), wiggers: text('Wiggers: olaylar', 'Wiggers: events') },
  calcium: [
    text('1 · T-tübül: L tipi Ca²⁺ kanalı açılır', '1 · T-tubule: L-type Ca²⁺ channel opens'),
    text('2 · RyR2: Ca²⁺ ile tetiklenen Ca²⁺ salınımı', '2 · RyR2: calcium-induced calcium release'),
    text('3 · Troponin C: kasılma başlar', '3 · Troponin C: contraction begins'),
    text('4 · SERCA2a: Ca²⁺ SR’ye geri alınır', '4 · SERCA2a: Ca²⁺ reuptake into the SR'),
    text('5 · NCX / PMCA: Ca²⁺ hücreden çıkar', '5 · NCX / PMCA: Ca²⁺ extrusion')
  ],
  calciumNotes: [
    text('Aksiyon potansiyeli sarkolemma ve T-tübülde yayılır. Az miktarda hücre dışı Ca²⁺, L tipi kanaldan dyadik aralığa girer.', 'The action potential propagates along the sarcolemma and T-tubule. A small extracellular Ca²⁺ influx enters the dyadic space through L-type channels.'),
    text('Giren Ca²⁺, sarkoplazmik retikulumdaki RyR2 kanallarını açar. Yerel Ca²⁺ kıvılcımları birleşerek sitozolik Ca²⁺ geçişini oluşturur.', 'Incoming Ca²⁺ opens RyR2 channels on the sarcoplasmic reticulum. Local calcium sparks sum into the cytosolic calcium transient.'),
    text('Ca²⁺ troponin C’ye bağlanır; aktin-miyozin etkileşimi mümkün olur. Çapraz köprü döngüsü ATP gerektirir. Elektriksel depolarizasyon ile mekanik kasılma aynı olay değildir.', 'Ca²⁺ binds troponin C, permitting actin-myosin interaction. Cross-bridge cycling requires ATP. Electrical depolarization and mechanical contraction are distinct events.'),
    text('Gevşeme için sitozolik Ca²⁺ azalmalıdır. SERCA2a, ATP kullanarak Ca²⁺’yı SR’ye pompalar; fosfolamban SERCA’yı düzenler. Ca²⁺ troponinden ayrılır.', 'Relaxation requires cytosolic Ca²⁺ to fall. SERCA2a uses ATP to pump Ca²⁺ into the SR; phospholamban regulates SERCA. Ca²⁺ dissociates from troponin.'),
    text('İleri yönlü NCX: 1 Ca²⁺ dışarı, 3 Na⁺ içeri. NCX doğrudan ATP kullanmaz; Na⁺ gradyanını Na⁺/K⁺-ATPaz sürdürür (3 Na⁺ dışarı, 2 K⁺ içeri). PMCA daha küçük bir ATP-bağımlı Ca²⁺ çıkış yoludur. Bu yollar SERCA ile eşzamanlı çalışır.', 'Forward NCX: 1 Ca²⁺ out, 3 Na⁺ in. NCX does not directly consume ATP; Na⁺/K⁺-ATPase maintains the Na⁺ gradient (3 Na⁺ out, 2 K⁺ in). PMCA is a smaller ATP-dependent calcium extrusion pathway. These routes operate alongside SERCA.')
  ],
  conduction: [text('SA başlangıcı · 0 ms', 'SA origin · 0 ms'), text('AV bölgesine ulaşma · ~30 ms', 'Arrival at AV region · ~30 ms'), text('Penetran His · ~120 ms', 'Penetrating His · ~120 ms'), text('Distal His ve dallar · ~160 ms', 'Distal His and branches · ~160 ms')],
  conductionNotes: [
    text('Sinüs düğümünün uyarısı atriyal miyokartta yayılır. İnternodal çizgiler tercih edilen yayılım yollarının şemasıdır; yalıtılmış üç özel insan iletim kablosu olarak yorumlanmamalıdır.', 'The sinus impulse spreads through atrial myocardium. Internodal lines depict preferential routes, not three isolated specialized human conduction cables.'),
    text('Geçiş hücreleri uyarıyı AV düğüme taşır. Yavaş AV iletimi, atriyal kasılma ile ventrikül kasılması arasındaki gecikmeye katkı sağlar.', 'Transitional cells convey the impulse to the AV node. Slow AV conduction contributes to the delay between atrial and ventricular contraction.'),
    text('AV düğüm → penetran His demeti. Fibröz AV iskeleti atriyum ve ventrikül miyokardını elektriksel olarak ayırır; normal AV iletim ekseni His üzerinden geçer. Aksesuar yol bu ayrımı aşabilir.', 'AV node → penetrating His bundle. The fibrous AV skeleton electrically separates atrial and ventricular myocardium; the normal AV conduction axis crosses through His. An accessory pathway can bypass this separation.'),
    text('Distal His sağ ve sol dallara, ardından Purkinje ağına devam eder. Görseldeki 0,03 / 0,12 / 0,16 saniye, SA başlangıcından itibaren yaklaşık öğretim zamanlarıdır; PA/AH/HV intervali veya klinik normal aralık değildir.', 'Distal His continues into right/left branches and the Purkinje network. The figure’s 0.03 / 0.12 / 0.16 seconds are approximate cumulative teaching times from SA onset, not PA/AH/HV intervals or clinical normal ranges.')
  ],
  pumpNote: text('Doluş basıncı artınca, diğer etkenler sabitken atım hacmi Frank-Starling ilişkisiyle artar; eğri plato yapar. Sağ ve sol eğrinin basınç ekseni, sırasıyla sağ ve sol atriyuma aittir. Seri bağlı kalpte kararlı durumda iki ventrikülün ortalama ileri debisi eşittir; aynı basınçta çizilen ayrı eğriler, eşzamanlı debi farkı değildir.', 'With other factors fixed, increasing filling pressure raises stroke volume through the Frank-Starling relation until a plateau. Right and left curves use right and left atrial pressure, respectively. In the serial circulation, steady-state mean forward outputs match; separate curves at equal pressures are not simultaneous output differences.'),
  toneNote: text('Sempatik uyarı hız ve kontraktiliteyi artırıp pompa eğrisini yukarı kaydırır. Vagal etki başlıca SA/AV düğümlerinde ve atriyumlardadır; ventriküle doğrudan güçlü negatif inotropi şeklinde yorumlanmamalıdır. Burada net pompa kapasitesi şematik gösterilir; venöz dönüş eğrisi yoktur.', 'Sympathetic activation raises rate and contractility, shifting the pump curve upward. Vagal effects primarily involve SA/AV nodes and atria, not strong direct ventricular negative inotropy. This illustrates net pumping capacity; no venous-return curve is included.'),
  pressureNote: text('Sabit doluş ve inotropi varsayımındaki basınç-yük örneği: yüksek çıkış basıncı debiyi düşürür. Görseldeki yaklaşık 160 / 250 mmHg noktaları ve L/dk platoları deneysel öğretim değerleridir; güvenli kan basıncı, normal aralık veya kişiye özgü eşik değildir. Arter basıncı, duvar stresinin yalnız bir bileşenidir.', 'Pressure-load example at fixed filling and inotropy: high outflow pressure lowers output. Approximate 160 / 250 mmHg landmarks and L/min plateaus in the supplied figure are experimental teaching values, not safe pressures, normal ranges or patient-specific thresholds. Arterial pressure is only one component of wall stress.'),
  pvNotes: [
    text('A → B: mitral açık, aort kapalı; hacim ESV’den EDV’ye artar. B’de mitral kapanır, S1 oluşumuyla ilişkilidir.', 'A → B: mitral open, aortic closed; volume rises from ESV to EDV. At B, mitral closure is associated with S1.'),
    text('B → C: iki kapak kapalı; basınç artar, hacim sabit. C’de LV basıncı aort basıncını aşar ve aort kapağı açılır.', 'B → C: both valves closed; pressure rises at fixed volume. At C, LV pressure exceeds aortic pressure and the aortic valve opens.'),
    text('C → D: aort açık, mitral kapalı; hacim azalır. D’de aort kapanır, S2 ile ilişkilidir. SV = EDV − ESV.', 'C → D: aortic open, mitral closed; volume falls. At D, aortic closure is associated with S2. SV = EDV − ESV.'),
    text('D → A: iki kapak kapalı; basınç düşer, hacim sabit. LV basıncı LA’nın altına indiğinde mitral açılır. İzovolümetrik kenarlar, ciddi regürjitasyonda kaybolabilir.', 'D → A: both valves closed; pressure falls at fixed volume. Mitral opens when LV pressure falls below LA pressure. True isovolumetric limbs may disappear with significant regurgitation.')
  ],
  energy: text('EW/SW: kapalı döngünün alanı = |∮P dV|, dış atım işi. PE: döngünün solunda, sistol sonu ve diyastolik ilişkiler arasında kalan potansiyel enerji; dışa atılan iş değildir. PVA = SW + PE. EDPVR pasif diyastolik ilişki; ESPVR sistol sonu ilişkisidir. Görseldeki geniş yeşil maksimum sistolik basınç eğrisi, doğrusal ESPVR ile aynı eğri değildir. SW, toplam metabolik enerji veya miyokart oksijen tüketimine eşit değildir.', 'EW/SW: enclosed loop area = |∮P dV|, external stroke work. PE: potential energy to the left of the loop between end-systolic and diastolic relations, not ejected external work. PVA = SW + PE. EDPVR is the passive diastolic relation; ESPVR is the end-systolic relation. The supplied broad green maximum systolic pressure curve is not the linear ESPVR. SW is not total metabolic energy or myocardial oxygen consumption.'),
  wiggers: text('Basınç, hacim, EKG ve sesler aynı zaman ekseninde. a: atriyal kasılma; c: erken ventrikül kasılmasında AV kapağın atriyuma doğru kabarması; v: AV kapak kapalıyken atriyal doluş. S1 AV kapanması, S2 semilunar kapanmasıyla ilişkilidir; normal kapak açılması sessizdir. S3 hızlı doluşta, S4 atriyal sistolde olabilir; erişkinlerin her atımında beklenen sesler değildir. AF’de organize a dalgası ve S4 yoktur.', 'Pressure, volume, ECG and sounds share one time axis. a: atrial contraction; c: AV valve bulging toward the atrium in early ventricular contraction; v: atrial filling with the AV valve closed. S1 relates to AV closure, S2 to semilunar closure; normal opening is silent. S3 may occur in rapid filling and S4 during atrial systole; neither is expected on every adult beat. AF lacks an organized a wave and S4.'),
  designed: text('Şematik öğretim çizimi; hasta kaydı değildir. Kaynak görsellerin baskısı belirtilmedi; sayısal eğriler veri olarak sayısallaştırılmadı.', 'Schematic teaching drawing, not a patient recording. Source image edition was not supplied; numeric curves were not digitized as data.')
};
