import { T, VASO_DRUGS as DRUGS, VASO_SCENARIOS as SCENARIOS, VASO_SOURCES as SOURCES, vasoPath } from './vasoactive-data.js';
import './vasoactive.css';
const esc = s => String(s).replace(/[&<>"']/g, c => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', '"':'&quot;', "'":'&#39;' }[c]));
export function createVasoactivePanel({ mount, getLang = () => 'tr' }) {
  let profile = 'pressure', scenario = 'septic', selected = 'norepinephrine', view = 'algorithm';
  const root = document.createElement('div'); root.className = 'vasolab'; mount.replaceChildren(root);
  root.innerHTML = `<header><p class="vaso-eyebrow"></p><h2></h2><p class="vaso-intro"></p></header><nav class="vaso-views"></nav>
  <section data-vaso-page="algorithm"><div class="vaso-entry"><strong></strong><p></p></div><div class="vaso-assess"><h3></h3><p></p></div><div class="vaso-profiles"></div><div class="vaso-flags"></div><div class="vaso-result" role="status"><h3></h3><p></p><div class="vaso-agents"></div><p class="vaso-context"></p></div></section>
  <section data-vaso-page="drugs" hidden><div class="vaso-drugs"></div><div class="vaso-drug-layout"><svg class="vaso-map" viewBox="0 0 600 310" role="img"><defs><marker id="vaso-head" markerWidth="8" markerHeight="8" refX="7" refY="4" orient="auto"><path d="M0 0L8 4L0 8Z" fill="#547965"/></marker></defs><rect x="10" y="10" width="580" height="290" rx="20" fill="#f1f5eb"/><path d="M175 112C120 44 56 99 94 158L175 242L256 158C294 99 230 44 175 112Z" class="vaso-heart"/><path d="M295 120H362Q389 120 404 146T450 172H572 M295 176H362Q389 176 404 202T450 228H572" class="vaso-vessel"/><path d="M228 146H318" class="vaso-flow" marker-end="url(#vaso-head)"/><text x="175" y="48" text-anchor="middle" data-map="pump"></text><text x="444" y="75" text-anchor="middle" data-map="vessel"></text><text x="175" y="272" text-anchor="middle" data-map="co"></text><text x="444" y="272" text-anchor="middle" data-map="svr"></text><text x="444" y="104" text-anchor="middle" data-map="target"></text></svg><article class="vaso-drug"><h3></h3><p class="vaso-target"></p><div class="vaso-effects"></div><h4 data-field="context"></h4><p data-value="context"></p><h4 data-field="risk"></h4><p data-value="risk"></p><details class="vaso-dose"><summary></summary><p></p><small></small></details><div class="vaso-drug-sources"></div></article></div><p class="vaso-legend"></p></section>
  <section data-vaso-page="scenarios" hidden><div class="vaso-scenarios"></div><article class="vaso-scenario"><h3></h3><p></p><strong></strong><button type="button" data-vaso-return></button></article></section>
  <section class="vaso-monitor"><h3></h3><div></div></section><details class="vaso-corrections"><summary></summary><ul></ul></details><details class="vaso-sources"><summary></summary><ul></ul></details>`;
  const $ = s => root.querySelector(s), text = (selector, value) => { $(selector).textContent = value; };
  const tr = x => x[getLang() === 'en' ? 'en' : 'tr'];
  const effectText = effect => effect.includes('dose-dependent') ? tr(T('Doza bağlı','Dose-dependent')) : effect.includes('variable') ? tr(T('Değişken','Variable')) : effect;
  const targetText = target => target.includes('α dominant') ? tr(T('α ağırlıklı','α dominant')) : target;
  const buttons = (parent, entries, action, attr) => new Map(entries.map(([id, title]) => {
    const b = document.createElement('button'); b.type='button'; b.dataset[attr]=id; b.addEventListener('click',()=>action(id)); $(parent).append(b); return [id,{ b,title }];
  }));
  const views = buttons('.vaso-views', [['algorithm',T('01 · Seçim haritası','01 · Selection map')],['drugs',T('02 · İlaç hedefleri','02 · Drug targets')],['scenarios',T('03 · Şok senaryoları','03 · Shock scenarios')]], id=>{view=id;refresh();},'vasoView');
  const profiles = buttons('.vaso-profiles', [['pressure',T('Basınç düşük → damar tonusu','Low pressure → vascular tone')],['output',T('Basınç yeterli, debi düşük → pompa','Adequate pressure, low output → pump')],['both',T('Basınç + debi düşük → birlikte değerlendir','Low pressure + output → assess both')]], id=>{profile=id;selected=vasoPath({profile,scenario}).agents[0];refresh();},'vasoProfile');
  const drugs = buttons('.vaso-drugs', DRUGS.map(d=>[d.id,d.name]),id=>{selected=id;refresh();},'vasoDrug');
  const scenarios = buttons('.vaso-scenarios',SCENARIOS.map(s=>[s.id,s.name]),id=>{scenario=id;refresh();},'vasoScenario');
  const flags = new Map();
  for (const [id,title] of [['escalating',T('Artan noradrenalin ihtiyacı','Escalating norepinephrine')],['tachy',T('Taşiaritmi','Tachyarrhythmia')],['renal',T('Böbrek işlevi bozuk','Renal impairment')]]) {
    const label=document.createElement('label'),input=document.createElement('input'),span=document.createElement('span');input.type='checkbox';input.dataset.vasoFlag=id;input.addEventListener('change',refresh);label.append(input,span);$('.vaso-flags').append(label);flags.set(id,{input,span,title});
  }
  $('[data-vaso-return]').addEventListener('click',()=>{view='algorithm';refresh();$('.vaso-profiles button[aria-pressed=true]').focus();});
  function sourceLink(id) { const a=document.createElement('a');a.href=SOURCES[id].url;a.textContent=SOURCES[id].title;a.target='_blank';a.rel='noopener noreferrer';return a; }
  for(const id of Object.keys(SOURCES)){const li=document.createElement('li');li.append(sourceLink(id));$('.vaso-sources ul').append(li);}
  function refresh() {
    text('.vaso-eyebrow',tr(T('HEMODİNAMİK DESTEK LABORATUVARI','HEMODYNAMIC SUPPORT LAB')));
    text('header h2',tr(T('Basınç mı, pompa mı, ikisi mi?','Pressure, pump, or both?')));
    text('.vaso-intro',tr(T('Erişkin şokta seçim mantığını keşfet. Profil bir öğretim varsayımıdır; hasta tanısı veya otomatik reçete oluşturulmaz.','Explore adult shock selection logic. Profiles are teaching assumptions; no patient diagnosis or automatic prescription.')));
    for(const [id,{b,title}] of views){b.textContent=tr(title);b.setAttribute('aria-pressed',String(view===id));$(`[data-vaso-page=${id}]`).hidden=view!==id;}
    for(const [id,{b,title}] of profiles){b.textContent=tr(title);b.setAttribute('aria-pressed',String(profile===id));}
    for(const [id,{b,title}] of drugs){b.textContent=tr(title);b.setAttribute('aria-pressed',String(selected===id));}
    for(const [id,{b,title}] of scenarios){b.textContent=tr(title);b.setAttribute('aria-pressed',String(scenario===id));}
    for(const {span,title} of flags.values())span.textContent=tr(title);
    text('.vaso-entry strong',tr(T('01 · Hipotansiyon / hipoperfüzyonu tanı','01 · Recognize hypotension / hypoperfusion')));
    text('.vaso-entry p',tr(T('MAP tek başına yeterli değil: mental durum, kapiller dolum, idrar ve laktat eğilimini birlikte değerlendir. Septik şok başlangıç MAP hedefi 65 mmHg; ≥65 yaşta SSC 2026, 60–65 mmHg aralığını önerir. Hedef bireyselleştirilir.','Assess mentation, capillary refill, urine and lactate trend together. Initial septic-shock MAP target: 65 mmHg; SSC 2026 suggests 60–65 mmHg at age ≥65. Individualize targets.')));
    text('.vaso-assess h3',tr(T('02 · Hemodinamik profili değerlendir','02 · Assess hemodynamic profile')));
    text('.vaso-assess p',tr(T('Neden, POCUS/eko ile LV–RV ve volüm durumu, ritim, konjesyon, perfüzyon. Soğuk ekstremite = yüksek SVR varsayımı güvenilir değil. Sıvı yanıtı ve toleransını yeniden değerlendir.','Cause, echo/POCUS LV–RV and volume status, rhythm, congestion and perfusion. Cold extremities do not reliably establish high SVR. Reassess fluid responsiveness and tolerance.')));
    const path=vasoPath({profile,scenario,escalating:flags.get('escalating').input.checked}),s=SCENARIOS.find(x=>x.id===scenario);
    text('.vaso-result h3',`${tr(s.name)} · ${tr(path.kind==='cause'?T('Önce nedeni düzelt','Correct cause first'):profile==='both'?T('Basınç desteği + seçilmiş inotropi','Pressure support + selected inotropy'):profile==='output'?T('Yeterli basınçta inotropiyi değerlendir','Assess inotropy at adequate pressure'):T('Vazopressör yolu','Vasopressor pathway'))}`);
    text('.vaso-result > p',tr(path.kind==='cause'?T('İlaçlar geçici destek olabilir; altta yatan nedeni tedavi etmenin yerine geçmez. Noradrenalin ancak süren hipotansiyonda seçilmiş köprü desteği.','Drugs may bridge care, never replace cause treatment. Norepinephrine is a selected bridge only for persistent hypotension.'):profile==='both'?T('İki ilaç herkes için gerekli değildir. Seçilmiş hastada perfüzyon, basınç ve pompa yanıtı birlikte izlenir.','Two drugs are not needed by everyone. Reassess perfusion, pressure and pump response together in selected patients.'):profile==='output'?T('İnotropi: kardiyak disfonksiyon ve yeterli volüm/basınca rağmen süren hipoperfüzyon koşulunda. MAP mevcut vazopressörle korunuyorsa dobutamin ona eklenir; yerine geçmez.','Inotropy requires cardiac dysfunction and persistent hypoperfusion despite adequate volume and pressure. If a pressor maintains MAP, dobutamine is added to it, not substituted.'):T('Noradrenalin basınç yolunun temel örneği. Artan gereksinimde septik şok için vazopressin eklenmesi değerlendirilir.','Norepinephrine is the base pressure-path example; consider adjunct vasopressin with escalating needs in septic shock.')));
    $('.vaso-agents').replaceChildren(...[...path.agents,...path.adjunct].map(id=>{const b=document.createElement('button');b.type='button';b.dataset.vasoAgent=id;b.textContent=tr(DRUGS.find(d=>d.id===id).name);b.addEventListener('click',()=>{selected=id;view='drugs';refresh();$('.vaso-drugs button[aria-pressed=true]').focus();});return b;}));
    const notes=[tr(s.cause)];
    if(scenario==='septic')notes.push(tr(T('MAP yine yetersizse adrenalin; kardiyak disfonksiyonda adrenalin de alternatif.','If MAP remains inadequate, epinephrine; also an alternative with cardiac dysfunction.')));
    if(flags.get('tachy').input.checked)notes.push(tr(T('Taşiaritmi: katekolamin yükü ve nedenleri kontrol et; fenilefrin düşük debiyi kötüleştirebilir.','Tachyarrhythmia: reassess catecholamines and causes; phenylephrine may worsen low output.')));
    if(flags.get('renal').input.checked)notes.push(tr(T('Böbrek: milrinon birikir; ürün bilgisine göre hız azaltımı gerekir.','Renal impairment: milrinone accumulates; label-directed rate reduction required.')));
    text('.vaso-context',notes.join(' · '));
    const d=DRUGS.find(x=>x.id===selected);text('.vaso-drug h3',tr(d.name));text('.vaso-target',targetText(d.target));
    $('.vaso-effects').replaceChildren(...d.effects.map((effect,i)=>{const e=document.createElement('div');const strong=document.createElement('strong');strong.textContent=effectText(effect);const label=document.createElement('span');label.textContent=['SVR','CO','HR'][i];e.append(strong,label);return e;}));
    for(const key of ['context','risk']){text(`[data-field=${key}]`,tr(key==='context'?T('Klinik bağlam','Clinical context'):T('Risk / izlem','Risk / monitoring')));text(`[data-value=${key}]`,tr(d[key]));}
    text('.vaso-dose summary',tr(T('Kaynak doz bilgisi · erişkin IV','Source dose information · adult IV')));text('.vaso-dose p',tr(d.dose));
    text('.vaso-dose small',tr(T('Karşılaştırmalı kaynak bilgisi; başlangıç, yükleme, seyreltme ve titrasyon protokolü değildir. Kurum protokolü ve ürün bilgisi gerekir.','Comparative reference information, not starting/loading, dilution or titration protocol. Use local protocols and product information.')));
    $('.vaso-drug-sources').replaceChildren(...d.sources.map(sourceLink));
    text('[data-map=pump]',tr(T('Kalp / kontraktilite','Heart / contractility')));text('[data-map=vessel]',tr(T('Sistemik damar tonusu','Systemic vascular tone')));text('[data-map=co]',`CO ${effectText(d.effects[1])}`);text('[data-map=svr]',`SVR ${effectText(d.effects[0])}`);text('[data-map=target]',targetText(d.target));
    $('.vaso-map').setAttribute('aria-label',`${tr(d.name)}: ${targetText(d.target)}; SVR ${effectText(d.effects[0])}, CO ${effectText(d.effects[1])}, HR ${effectText(d.effects[2])}`);
    $('.vaso-heart').classList.toggle('is-active',d.effects[1].includes('↑'));$('.vaso-vessel').classList.toggle('is-active',d.effects[0].includes('↑'));
    text('.vaso-legend',tr(T('Oklar tipik yönü gösterir; etki büyüklüğü, doz-yanıt veya sağkalım faydası değildir. MAP ≈ CO × SVR + CVP; yalnız MAP yükselmesi perfüzyon düzeldi demek değildir.','Arrows show typical directions, not magnitude, dose-response or survival benefit. MAP ≈ CO × SVR + CVP; a higher MAP alone does not prove restored perfusion.')));
    text('.vaso-scenario h3',tr(s.name));text('.vaso-scenario p',tr(s.detail));text('.vaso-scenario strong',tr(s.cause));text('[data-vaso-return]',tr(T('Bu senaryoyu seçim haritasında aç','Open this scenario in selection map')));
    text('.vaso-monitor h3',tr(T('Yanıtı tekrar değerlendir','Reassess response')));
    const monitors=[T('Basınç + perfüzyon','Pressure + perfusion'),T('İdrar eğilimi; yaklaşık ≥0,5 ml/kg/saat sık kullanılan izlem eşiği, tek hedef değil','Urine trend; ≥0.5 ml/kg/h is a common monitoring threshold, not sole target'),T('Laktat eğilimi + kapiller dolum + mental durum','Lactate trend + capillary refill + mentation'),T('EKG/aritmi, iskemi, periferik damar yolu','ECG/arrhythmia, ischemia, peripheral access'),T('POCUS/LV–RV, volüm, elektrolitler; stabil oldukça desteği azalt','POCUS/LV–RV, volume, electrolytes; reduce support as stable')];
    $('.vaso-monitor > div').replaceChildren(...monitors.map((m,i)=>{const p=document.createElement('p');p.textContent=`0${i+1} · ${tr(m)}`;return p;}));
    text('.vaso-corrections summary',tr(T('Referans görselde yapılan düzeltmeler','Corrections to supplied image')));
    const corrections=[T('Anjiyotensin II: görseldeki 0,01–0,08 aralık/birim eşleşmesi ürün bilgisine uymuyor; GIAPREZA başlangıcı 20 ng/kg/dk.','Angiotensin II: image’s 0.01–0.08 range/unit pairing does not match labeling; GIAPREZA starts at 20 ng/kg/min.'),T('Her şokta rutin sıvı veya iki ilaç yok. Konjesyon, sıvı yanıtı ve temel neden önce değerlendirilir.','Neither routine fluids nor two drugs apply to every shock. Assess congestion, fluid response and underlying cause.'),T('Fenilefrin taşiaritmi için otomatik çözüm değil. Levosimendan septik şokta önerilmez; dopamin renal koruma için kullanılmaz.','Phenylephrine is not an automatic tachyarrhythmia solution. Levosimendan is discouraged in septic shock; dopamine is not used for renal protection.'),T('Aralıklar ürün ve bağlama göre değişir; görseldeki tüm aralıklar evrensel protokol olarak aktarılmadı. SSC 2026 yaşa bağlı MAP hedefi eklendi.','Ranges vary by product and context; image ranges were not copied as universal protocols. SSC 2026 age-specific MAP target added.')];
    $('.vaso-corrections ul').innerHTML=corrections.map(x=>`<li>${esc(tr(x))}</li>`).join('');text('.vaso-sources summary',tr(T('Kaynaklar · kontrol: 4 Ekim 2026','Sources · checked 4 October 2026')));
  }
  refresh();return { refresh };
}
